name: Build Plugin after Release published

on:
  release:
      types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build zip file
        run: ./create-zip.sh
      - name: Upload app tarball to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: friendly-captcha.zip 
          asset_name: friendly-captcha.zip 
          tag: ${{ github.ref }}
          overwrite: true